initial_player_assets:
  points: 500
  energy: 48
  ambers: 0
player_limits:
  points: 500
  energy: 48
  referrals: 10
full_recovery_time: # in ms
  points: 86400000
  energy: 86400000
referral_rewards: # in ambers
  premium: 10000
  normal: 5000
action_price:
  full_charge_points: 12 # in energy
